lib/google/ads/google_ads/google_ads_client.rb
When attempting to run [this example](https://github.com/googleads/google-ads-ruby/blob/85eff72797e0c1a9a7d557366de6932c869affb1/examples/account_management/get_account_information.rb), the following error is raised:
```
NameError (uninitialized constant Google::Ads::GooglAads)
```
In [`Google::Ads::GoogleAds::GoogleAdsClient`](https://github.com/googleads/google-ads-ruby/blob/a8553de62943608850bdcec58208e80d20d56e94/lib/google/ads/google_ads/google_ads_client.rb#L147), `Google::Ads::GoogleAds` is misspelled as `Google::Ads::GooglAads`.
This PR fixes this typo.
- https://github.com/googleads/google-ads-ruby/issues/10
=> Fix typo in GoogleAdsClient

google-ads-googleads.gemspec
Bundler 2 has been released, nothing in our `Gemfile` prevents this project from working with both versions of bundler, and we haven't committed `Gemfile.lock` (which is fine because this is a library and not an application). This commit relaxes the gemspec pin on bundler to allow installs with bundler 2, but will not automatically add bundler 3 (should they ever release that).
=> Relax pin to allow bundler 2.

examples/targeting/add_customer_negative_criteria.rb
ported from [this soap example](https://github.com/googleads/google-api-ads-ruby/blob/master/adwords_api/examples/v201809/targeting/add_customer_negative_criteria.rb)
=> Create an "Add Customer Negative Criteria" example

lib/google/ads/google_ads/google_ads_client.rb
Fixes an operator precedence bug:
```
irb(main):002:0> "hello".is_a? Integer || 1 == 1
=> false
irb(main):003:0> "hello".is_a?(Integer) || 1 == 1
=> true
```
=> fix operator precedence bug when detecting invalid login_customer_id

lib/google/ads/google_ads/logging_interceptor.rb, test/test_logging_interceptor.rb
Also fixes a bug where v1 errors were not printing debug info.
=> Add tests around the logging interceptor

lib/google/ads/google_ads/google_ads_client.rb, lib/google/ads/google_ads/logging_interceptor.rb, lib/google/ads/google_ads/partial_failure_error_decoder.rb, test/test_google_ads_client.rb, test/test_logging_interceptor.rb
Also implements logging for the partial failure error messages at the
WARN level.
So for example if a user makes a request:
```ruby
response = media_file_service.mutate_media_files(
customer_id,
[
media_file_logo_op,
media_file_marketing_image_op,
],
partial_failure: true,
validate_only: true,
)
```
they can then say
```ruby
Google::Ads::GoogleAds::PartialFailureDecoder.decode(
response.partial_failure_error
)
```
and they weill get back fully hydrated typed protos with full
information about what went wrong, in this case, see the attached new
test for the logging interceptor for exactly what comes out the other
side.
The reason that this doesn't use the `EXCEPTION_TRANSFORMER` is that we
don't get an exception raised when a partial failure occurs, and I
think we shouldn't, rather leaving …
=> Add class for dealing with partial_failure_error

lib/google/ads/google_ads/logging_interceptor.rb
A user who gets a partial failure response must have specifically requested it, and this log level matches the other extended information fields for otherwise successful requests.
=> Changing the log level for partial failure errors to DEBUG

lib/google/ads/google_ads/utils/v1/proto_lookup_util.rb
This was created originally as `ExtensionFeedItemOperation`, but that
doesn't quite match the uniform pattern that we use, so this adds the
extra value, so that we don't break anyone who's already using it, but
the consistent value is available.
=> Add `ExtensionFeedItem` as an operation look up

examples/error_handling/handle_partial_failures.rb
Output looks like:
```
Created ad group criterion with id customers/blah/adGroupCriteria/blah
Created ad group criterion with id customers/blah/adGroupCriteria/blah
error occured creating criterion operations[1] > create > keyword > text with value: inv@lid cruise because keyword text has invalid characters or symbols.
error occured creating criterion operations[3] > create > keyword > text with value: b(a)d keyword cruise because keyword text has invalid characters or symbols.
```
=> Add an partial failure error handling example.

Rakefile, scripts/validate_protos.rb
Building on top of #80 this adds a script which loads every proto file and causes rake to terminate *after* patching all the proto files.
This way, we get validation that all the protos in the library are actually well formed and loadable.
=> Validate all protos are loadable

lib/google/ads/google_ads/google_ads_client.rb
Pierrick was having some trouble with having a string that was actually
an integer, so this will force cast to the right value. Given that we
don't type check in configuration this ought to cleanly solve the
problem.
=> Force cast customer IDs to integers if they are of another type.

lib/google/ads/google_ads/autoboxing_fields.rb, test/test_autoboxing_fields.rb
This reverts commit 15a1108c2f22c5a059251692bfa76ec58eecdc37.
=> Revert "Make autoboxing fields work with constructors (#126)"

lib/google/ads/google_ads/google_ads_client.rb, lib/google/ads/google_ads/lookup_service.rb, lib/google/ads/google_ads/service_lookup.rb
This is a preparatory refactoring for allowing us to pass our own channels in to the code gax creates. We're doing this so that we can set the maximum message size on the channel to 64mb. To do this we need to pass a `GRPC::Core::Channel` in the position that `credentials` currently occupies. The problem that we have right now is that we've got two different ways of creating services. Until we've done some open source stuff, we can't merge that PR.
SO
this PR applies the "method object" refactoring to pull the (ever expanding) `Google::Ads::GoogleAdsClient#service` method out in to it's own object in the first commit, and then just applies the extract method refactoring over and over again. This basically is just to reduce the cognitive overhead of swapping in a grpc channel instead of an …
=> Extract service creation

google_ads_config.rb, lib/google/ads/google_ads/config.rb
This works by setting the environment variable that [GRPC uses](https://github.com/grpc/grpc/blob/master/src/core/ext/filters/client_channel/http_proxy.cc)
when the user specifies it on their configuration file.
=> Adds very simple support for a HTTP proxy.

Rakefile
Previously I was running `bundle exec rake build` to make the gem usable
from scratch. However, this is not actually ideal for dev/testing.
Codegen needs patch and third party code, so this better expresses the
real dependencies that we have so that we can build for dev without
having to actually compile a gem.
=> Fix codegen dependencies.

examples/hotel_ads/add_hotel_ad.rb
There was a change for Hotels that causes an error when setting `AdGroupAd` to `PAUSED` and should always be `ENABLED`.  Setting `AdGroupAd`'s status to `PAUSED` will now throw a `OPERATION_NOT_PERMITTED_FOR_CAMPAIGN_TYPE`, this is expected as the status for `AdGroupAd` for Hotel campaigns should always be `ENABLED`.
=> Fixing AdGroupAd status to be ENABLED

examples/hotel_ads/add_hotel_ad.rb
- Adding comment about why ad group ad should be enabled for hotels, originally brought up in https://github.com/googleads/google-ads-dotnet/pull/123#discussion_r352711245
=> Adding comment for ad group ad status

examples/planning/get_ad_group_criterion_cpc_bid_simulations.rb
This example gets all available ad group criterion CPC bid simulations for a given ad group.
=> Added get_ad_group_criterion_cpc_bid_simulations.rb

codegen/templates/operations.rb.erb, examples/campaign_management/add_complete_campaigns_using_batch_job.rb, test/test_object_creation.rb
- support block syntax for client.operation.operation_name
- support direct creation without block for client.operation.create_resource.resource_type
resolves #225, resolves #227
=> fix block syntax for operations (issue #225 and #227)

examples/shopping_ads/add_shopping_product_ad.rb, examples/shopping_ads/add_shopping_product_listing_group_tree.rb, examples/shopping_ads/add_shopping_smart_ad.rb
Closes #265 
```console
ruby examples/shopping_ads/add_shopping_product_ad.rb --create-default-listing-group true
ruby examples/shopping_ads/add_shopping_product_ad.rb --create-default-listing-group false
ruby examples/shopping_ads/add_shopping_product_listing_group_tree.rb --replace-existing-tree true
ruby examples/shopping_ads/add_shopping_product_listing_group_tree.rb --replace-existing-tree false
ruby examples/shopping_ads/add_shopping_smart_ad.rb  --create-default-listing-group true
ruby examples/shopping_ads/add_shopping_smart_ad.rb  --create-default-listing-group  false
=> Switch example CLI arguments to boolean (#265)

examples/remarketing/upload_conversion_enhancement.rb
restatement_value and its fields are ignored by Ads for adjustments of type ENHANCEMENT
=> Remove restatement currency code and value from enhanced conversions example

examples/advanced_operations/add_call_ad.rb, examples/advanced_operations/add_smart_campaign.rb, examples/extensions/add_call.rb, examples/remarketing/add_customer_match_user_list.rb, examples/remarketing/upload_call_conversion.rb, examples/remarketing/upload_conversion_enhancement.rb, examples/remarketing/upload_store_sales_transactions.rb
Our examples use some email addresses that are not recommended based on Google documentation (https://developers.google.com/style/examples#example-domain-names). We need to update them per conventions.
=> Update example emails, names, phones, and addresses

examples/travel/add_things_to_do_ad.rb
Tested with:
```
ruby examples/travel/add_things_to_do_ad.rb -C <customer-id> -T <things-to-do-center-id>
```
Can share more info internally if needed.
=> Add Things To Do campaign example

lib/google/ads/google_ads/interceptors/logging_interceptor.rb
This PR fixes (I think) a bug where the Customer ID is being overridden incorrectly by the resource ID in the logs.
The current bug with this behaviour is the Customer ID is being logged incorrectly for some requests such as checking offline user jobs which have the resource name in this format:
```
/customers/{customer_id}/offlineUserDataJobs/{job_id}
```
Right now, the `customer_id` will be set to `job_id`, which is wrong. 
I think the logic is meant to be, "only use the resource name if the customer ID is _not_ set", rather than defaulting to using the resource name to derive the Customer ID all the time.
This PR attempts to make that change.
=> Only use resource_name when customer_id isn't already set

examples/account_management/approve_merchant_center_link.rb, examples/account_management/reject_merchant_center_link.rb, examples/misc/upload_image.rb, examples/misc/upload_media_bundle.rb
Pins/Downgrades these examples to V14 since services have been removed in V15:
- accountmanagement/ApproveMerchantCenterLink
- accountmanagement/RejectMerchantCenterLink
- misc/UploadImage
- misc/UploadMediaBundle
=> Pin deprecated APIs to V14

examples/shopping_ads/get_product_category_constant.rb
Renaming to ProductCategoryConstant for V15.
=> Update V15 example ProductCategoryConstant

lib/google/ads/google_ads/google_ads_client.rb, test/test_google_ads_client.rb
Removes a check we for the `impersonate` field in order to make it work as expected: By only settings the `keyfile` field.
=> Support direct access with Service Account

examples/remarketing/add_customer_match_user_list.rb
As announced in [this blog post](https://ads-developers.googleblog.com/2025/02/update-to-customer-match-membership.html), we will soon disallow setting `membership_life_span` to no expiration.
Updated the comment to reflect this change.
=> Remove the reference for setting Customer Match membership to no expiration

.bundle/config, .gitignore, .rubocop.yml, Gemfile, examples/account_management/create_customer.rb, examples/advanced_operations/add_ad_customizer.rb, examples/basic_operations/add_ad_groups.rb, examples/billing/get_invoices.rb, examples/campaign_management/add_campaign_labels.rb, examples/planning/generate_keyword_ideas.rb, examples/remarketing/add_conversion_action.rb, examples/shared/error_handler.rb
I extracted the common Google Ads API error handling logic from the example scripts into a shared module: `examples/shared/error_handler.rb`.
This new module, `GoogleAdsErrorHandler`, provides a centralized method, `handle_google_ads_error`, for printing detailed error information from `Google::Ads::GoogleAds::Errors::GoogleAdsError` exceptions.
I updated the following example scripts to use the shared error handler:
- examples/account_management/create_customer.rb
- examples/advanced_operations/add_ad_customizer.rb
- examples/basic_operations/add_ad_groups.rb
- examples/campaign_management/add_campaign_labels.rb
- examples/remarketing/add_conversion_action.rb
- examples/billing/get_invoices.rb
- examples/planning/generate_keyword_ideas.rb
This change improves code maintainability by …
=> I've refactored the common error handling in the example scripts.

README.md, google-ads-googleads.gemspec
**Problem**
`google-ads-ruby` cannot be installed when using Ruby 3.4.x. This is due to the locking of the upper bound version of `google-protobuf` dependency to `< 4.0.0` and `gapic-common` dependency to `< 1.0.0`. 
**Solution**
Bump the upper bound version lock of both of the aforementioned dependencies one major version, thus allowing for `>= 4.0.0` of `google-protobuf` and `>= 1.0.0` of `gapic-common`.
- Unlock gapic-common from < 1.0.0 to < 2.0.0.
- Unlock google-protobuf from < 4.0.0 to < 5.0.0.
- google-protobuf 4.0.0 is required for Ruby 3.4 compatibility.
Resolves https://github.com/googleads/google-ads-ruby/issues/502
**Tophatting**
Before (Ruby 3.3.x installs fine, Ruby 3.4.x fails to install)
After (Ruby 3.4.x installs fine, using this branched version)
Testing - Simply ran …
=> Fix support for Ruby 3.4

Gemfile
While working on https://github.com/googleads/google-ads-ruby/pull/515 I came across this message in my terminal while running tests.
```console
/home/larouxn/.gem/ruby/3.4.3/gems/activesupport-6.1.7.10/lib/active_support/core_ext/benchmark.rb:3: warning: benchmark was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
```
At first I thought we needed to do something with the `benchmark` gem but that's when I realized this gem is still only requiring `~> 6.1` of `activesupport`. Support for 6.1 ended about 7 months ago. Thus, I'm proposing we raise the minimum requirement to 7.1, which is still supported for the next almost 5 months. ([EOL info](https://endoflife.date/rails))
Testing
=> Bump activesupport requirement from 6.1 to 7.1 as the former is EOL

CHANGELOG.md, lib/google/ads/google_ads/version.rb
Change-Id: I8cdd10edabd8b4770af0e9057275ae5e252c93bb
These changes are needed to create a release for [PR#515](https://github.com/googleads/google-ads-ruby/pull/515) and [PR#517](https://github.com/googleads/google-ads-ruby/pull/517)
=> Updating version and CHANGELOG in preparation for minor release
