googleads/google-ads-ruby

- ChangeLog
- google_ads_config.rb
- lib/google/ads/google_ads/config.rb
- lib/google/ads/google_ads/google_ads_client.rb
- lib/google/ads/google_ads/logging_interceptor.rb
- lib/google/ads/google_ads/version.rb
Change-Id: Iee921af43deabe8c6af070917a70ec124255043e
> Initial pass to add logging support.

- lib/google/ads/google_ads/google_ads_client.rb
https://github.com/googleads/google-ads-ruby/issues/23
> Header values must be strings

- lib/google/ads/google_ads/logging_interceptor.rb
https://github.com/googleads/google-ads-ruby/issues/22
> NPE for status_details

- ChangeLog
- lib/google/ads/google_ads/logging_interceptor.rb
- lib/google/ads/google_ads/version.rb
> Fixing logging interceptor for customer service requests.

- lib/google/ads/google_ads.rb
- lib/google/ads/google_ads/google_ads_client.rb
- lib/google/ads/google_ads/lookup_util.rb
- test/test_google_ads.rb
- test/test_google_ads_client.rb
- test/test_lookup_util.rb
- test/test_path_lookup_util.rb
> move lookup_util to its own class

- Gemfile
This will be useful for building examples by dropping a repl in to work
with response values.
> Add the pry debugger to the Gemfile.

- lib/google/ads/google_ads/google_ads_client.rb
Fixes #31. Please let me know if there is an example test I can use to add a test for this
> only add LoggingInterceptor if logger exists

- lib/google/ads/google_ads.rb
- lib/google/ads/google_ads/api_versions.rb
- lib/google/ads/google_ads/logging_interceptor.rb
- test/test_logging_interceptor.rb
Each refactor is broken in to it's own commit, also fixes a circular require between google_ads.rb and google_ads/logging_interceptor.rb
> Refactor logging interceptor

- google_ads_config.rb
- lib/google/ads/google_ads/config.rb
- lib/google/ads/google_ads/google_ads_client.rb
- lib/google/ads/google_ads/logging_interceptor.rb
- test/test_google_ads_client.rb
> Make logger fully injectable

- examples/account_management/list_accessible_customers.rb
Change-Id: Ia1988fc6a66824fb92e1bd753243e8fc6bf138e7
> Adding example that lists accessible customers.

- examples/recommendations/dismiss_recommendation.rb
Change-Id: I3d0b4f0bd47742f54e0e6f1eceeb38730c47d68b
> Adding example to dismiss a recommendation.

- examples/account_management/create_customer.rb
Change-Id: Ifb7eacc8e94d0e3557f0a87d1ab91a89a8876457
> Adding example to create a customer.

- ChangeLog
- lib/google/ads/google_ads/version.rb
Change-Id: If6f434880e1b516a8e2fb42b66bf3595aa5c4def
> Updating version/changelog for release.

- lib/google/ads/google_ads/v1/enums/payment_mode_pb.rb
- lib/google/ads/google_ads/v1/resources/campaign_pb.rb
- lib/google/ads/google_ads/v1/resources/recommendation_pb.rb
Change-Id: I23927f280480644fca38566dca5c507fee17f8d4
> Newest proto changes for v1_1.

- examples/advanced_operations/add_dynamic_search_ads_campaign.rb
Based off: https://github.com/googleads/google-api-ads-ruby/blob/master/adwords_api/examples/v201809/advanced_operations/add_dynamic_search_ads_campaign.rb
> Add an example for creating a dynamic search ads campaign

- examples/planning/add_keyword_plan.rb
- examples/planning/generate_forecast_metrics.rb
Change-Id: Ie204163ad61a05ff61d1ef129b025e391b0d6c6d
> Adding keyword traffic estimation examples.

- README.md
Change-Id: If48f096f9c7dcefb5400a1eab745832787374d5a
> Removing references to AdWords from README.

- Gemfile
- examples/migration/campaign_management/create_complete_campaign_adwords_api_only.rb
- examples/migration/campaign_management/create_complete_campaign_both_apis_phase_1.rb
- examples/migration/campaign_management/create_complete_campaign_both_apis_phase_2.rb
- examples/migration/campaign_management/create_complete_campaign_both_apis_phase_3.rb
- examples/migration/campaign_management/create_complete_campaign_both_apis_phase_4.rb
- examples/migration/campaign_management/create_complete_campaign_google_ads_api_only.rb
This is WIP, but I wanted to get the first example solid before we move on to the "phases"
> Add the soap only example for migration.

- lib/google/ads/google_ads/utils/v0/path_lookup_util.rb
- lib/google/ads/google_ads/utils/v1/path_lookup_util.rb
- test/test_path_lookup_util.rb
Change-Id: I0b507e7c0ed559c61e7940507840ea8b20c5ced8
> Fixing path lookup utils for campaign shared sets.

- ChangeLog
- lib/google/ads/google_ads/version.rb
Change-Id: Ibe1b12339031dd209fbf12007f299c12a95093ea
> Version bump for release.

- google_ads_config.rb
- lib/google/ads/google_ads/config.rb
- lib/google/ads/google_ads/google_ads_client.rb
- test/test_google_ads_client.rb
> Allow users to pass custom authentication when creating a service.

- google_ads_config.rb
- lib/google/ads/google_ads/config.rb
- lib/google/ads/google_ads/google_ads_client.rb
- test/fixtures/keyfile.json
- test/test_google_ads_client.rb
Change-Id: Id6464a5e82add81569e6004867c751bc836c73dd
> Adding explicit service account support.

- examples/campaign_management/add_campaign_draft.rb
Change-Id: I0ed8e93890bbcc71f678937c6af8c9da45b38434
> Example for adding a campaign draft.

- examples/campaign_management/graduate_campaign_experiment.rb
Change-Id: Iaa34173b542333e1bce1cadeee0d28f3d344cefc
> Example showing how to graduate a campaign experiment.

- ChangeLog
- lib/google/ads/google_ads/version.rb
Change-Id: Ic7f9331827d34168b488b9b7ccde8127d385954b
> Update to version 2.4.0

- codegen/spec/filters_spec.rb
- codegen/src/filters.rb
> Fix update vs create class handling

- examples/basic_operations/add_ad_groups.rb
- examples/basic_operations/add_campaigns.rb
- examples/basic_operations/add_expanded_text_ads.rb
- examples/basic_operations/add_keyword.rb
- examples/basic_operations/get_ad_groups.rb
- examples/basic_operations/get_artifact_metadata.rb
- examples/basic_operations/get_campaigns.rb
- examples/basic_operations/get_expanded_text_ads.rb
- examples/basic_operations/get_keywords.rb
- examples/basic_operations/pause_ad.rb
- examples/basic_operations/remove_ad.rb
- examples/basic_operations/remove_ad_group.rb
- examples/basic_operations/remove_campaign.rb
- examples/basic_operations/remove_keyword.rb
- examples/basic_operations/update_ad_group.rb
- examples/basic_operations/update_campaign.rb
- examples/basic_operations/update_keyword.rb
Change-Id: I6244b4d40b0cf8e732e22f33b167af9cf36ec26a
> Updating all basic_operation examples to use factories.

- examples/account_management/create_customer.rb
- examples/account_management/get_account_changes.rb
- examples/account_management/get_account_information.rb
- examples/account_management/link_manager_to_client.rb
- examples/account_management/list_accessible_customers.rb
Change-Id: Iea0dd8742264afcc7c76d39ecea96002bf344ab3
> Updating account management examples to use factories.

- examples/advanced_operations/add_ad_group_bid_modifier.rb
- examples/advanced_operations/add_dynamic_page_feed.rb
- examples/advanced_operations/add_dynamic_search_ads_campaign.rb
- examples/advanced_operations/add_expanded_text_ad_with_upgraded_urls.rb
- examples/advanced_operations/add_gmail_ad.rb
- examples/advanced_operations/create_and_attach_shared_keyword_set.rb
- examples/advanced_operations/find_and_remove_criteria_from_shared_set.rb
- examples/advanced_operations/get_ad_group_bid_modifiers.rb
- examples/advanced_operations/use_portfolio_bidding_strategy.rb
Change-Id: Id92fbcfca83b5d87ae0117aee09d864cd244f233
> Updating advanced operations examples to use factories.

- examples/reporting/campaign_report_to_csv.rb
- examples/reporting/get_hotel_ads_performance.rb
- examples/reporting/get_keyword_stats.rb
Change-Id: I4f5bba5cf39bab6b1bad6e9edee1c43ce67269fb
> Rework reporting examples to use factories.

- examples/remarketing/add_conversion_action.rb
Change-Id: Ib914814f403d6cb2d043a577380cb9ce1bb05abb
> Updating remarketing example to use factories.

- examples/recommendations/apply_recommendation.rb
- examples/recommendations/dismiss_recommendation.rb
- examples/recommendations/get_text_ad_recommendations.rb
Change-Id: I8615c29fb9080cfabb9a8451a156cdbe9b200ff6
> Migrate recommendation examples to factories.

- examples/planning/add_keyword_plan.rb
- examples/planning/generate_forecast_metrics.rb
- examples/planning/generate_keyword_ideas.rb
Change-Id: I20df444f8a935599e9372446db4b591a43319687
> Updating planning examples to use factories.

- examples/error_handling/handle_partial_failure.rb
Change-Id: I22f80c271eea435b69b1add18bc29aedd2424c75
> update error example for factories.

- examples/hotel_ads/add_hotel_ad.rb
- examples/hotel_ads/add_hotel_ad_group_bid_modifiers.rb
Change-Id: I1b68cb259ca48dfb9d1e4cfeea98c65dbdf60468
> updating hotel ads examples for factories

- lib/google/ads/google_ads/utils/v2/path_lookup_util.rb
- test/test_path_lookup_util.rb
Change-Id: I1690019f652beea5c5ea25a62fed417dc115cfef
> Adding new ad service to path lookup util.

- lib/google/ads/google_ads/service_lookup.rb
> Fix the error transformer for the v2 error

- lib/google/ads/google_ads/google_ads_client.rb
Change-Id: I649cca1edc400d41db105cb2736d10de79e55ae4
> Adding explicit delegate dependency.

- README.md
Resolves #186
The syntax has been changed and the examples have been updated. There's one left in the README to update
> Update README to show syntax for fetching a specific service

- examples/advanced_operations/add_dynamic_search_ads.rb
- examples/basic_operations/add_keywords.rb
- examples/targeting/get_geo_target_constants_by_names.rb
Change-Id: I9d292a6f14a30e9f2ba1234c6a89c9a1dbc00234
> Updating example names to match other libraries.

- examples/basic_operations/get_ad_groups.rb
> minor fix for get_ad_groups

- ChangeLog
- lib/google/ads/google_ads/version.rb
Change-Id: I9f9a45b59152047cb303ac5f045e26db5dc87dbe
> Bumping version and ChangeLog for v3_1.

- lib/google/ads/google_ads/autoboxing_fields.rb
The original implementation would scan the list of fields and repeated fields on each instantiation, looking for ones that match what the user passed in. The new implementation stores the data for fields and repeated fields in a hash for quick lookup on kwarg name, and then only looks at the ones relevant to the user's request.
Also if the user passes no kwargs, it skips the whole thing.
> Fixing performance of autoboxing fields

- ChangeLog
- lib/google/ads/google_ads/version.rb
Change-Id: I6a5eac33327cc49fe4c55fc43f2f380f6c0fa9e9
> Version bump for v4 release.

- ChangeLog
- lib/google/ads/google_ads/version.rb
Change-Id: I2111c1f9c9d3df21e743d1c554c6f774c546d1c8
> Version bump for v5 release.

- examples/remarketing/upload_offline_conversions.rb
Change-Id: I6e3e315d3dbc32573a4a2f32c8cebbc5807dbd53
> Adding upload offline conversion example.

- examples/account_management/approve_merchant_center_link.rb
- examples/remarketing/add_customer_match_user_list.rb
- examples/remarketing/upload_call_conversion.rb
- examples/targeting/search_for_language_and_carrier_constants.rb
- approve_merchant_center_link
- add_customer_match_user_list
- upload_call_conversion
- search_for_language_and_carrier_constants
> Add 4 code examples

- examples/campaign_management/create_campaign_experiment.rb
- examples/campaign_management/graduate_campaign_experiment.rb
Change-Id: I8846c50e0eddc7c47b342b2f0819aa5d395ed0f9
> Updating experiment examples to use IDs instead of resource names.

- examples/error_handling/handle_expanded_text_ad_policy_violations.rb
- examples/error_handling/handle_keyword_policy_violations.rb
Change-Id: Ibcd7c2fe0132f6b15fba57a9ac1be8c1dec2b404
> Adding policy violation handling examples.

- examples/billing/add_billing_setup.rb
- examples/extensions/add_geo_target.rb
- examples/remarketing/add_logical_user_list.rb
- lib/google/ads/google_ads/utils/path_lookup_config.rb
add_billing_setup.rb
add_geo_target.rb
add_logical_user_list.rb
> add 3 code examples

- examples/advanced_operations/add_dynamic_search_ads.rb
Change-Id: Id52e823df74529bb353ca5510ce930e2b345c6fe
> Removing errant debug code from example.

- examples/campaign_management/validate_text_ad.rb
Change-Id: Ic2a8fca829bc6f393abebd609cf60427ecc74fd7
> Adding validate text ad example.

- examples/campaign_management/create_campaign_experiment.rb
- examples/campaign_management/graduate_campaign_experiment.rb
Change-Id: I718436e68cea8c65664b42dd3858d9d5a62a4d18
> Updating arg names for experiment examples.

- examples/advanced_operations/add_ad_customizer.rb
- examples/remarketing/upload_store_sales_transactions.rb
add_ad_customizer.rb
upload_store_sales_transactions.rb
> Add two code examples

- ChangeLog
- lib/google/ads/google_ads/version.rb
Change-Id: I6308661f02fee4ca705309be770957aab429164e
> Version bump for v6.

- examples/extensions/add_hotel_ad_group_bid_modifiers.rb
- examples/extensions/remove_entire_sitelink_campaign_extension_setting.rb
examples/extensions/add_hotel_ad_group_bid_modifiers.rb
examples/extensions/remove_entire_sitelink_campaign_extension_setting.rb
> added two code examples add_hotel_ad_group_bid_modifiers.rb and remove_entire_sitelink_campaign_extension_setting.rb

- examples/advanced_operations/add_local_campaign.rb
- examples/error_handling/handle_rate_exceeded_error.rb
examples/advanced_operations/add_local_campaign.rb
examples/error_handling/handle_rate_exceeded_error.rb
> added two code examples: add_local_campaign.rb and handle_rate_exceeded_error.rb

- examples/misc/upload_media_bundle.rb
Change-Id: I86745b1c8b9f0322ec5ead7c90fa42d29e7db1f9
> Renaming method in media bundle example to match file name.

- lib/google/ads/google_ads/interceptors/logging_interceptor.rb
- test/test_logging_interceptor.rb
Change-Id: I0a6c847fdba1ebeb7cb550959302711c6d8b3c6c
> Updating log sanitization to include a few more email address fields.

- examples/extensions/update_sitelink.rb
Change-Id: Id79c9e91f8ec807f5798777bbd7010dc200d5aa7
> Adding update sitelink example.

- examples/account_management/reject_merchant_center_link.rb
- examples/feeds/remove_feed_items.rb
Same files from the PR from September https://github.com/googleads/google-ads-ruby/pull/240
To avoid the merge issue.
> add two code examples reject_merchant_center_link.rb and remove_feed_items.rb

- examples/advanced_operations/add_ad_customizer.rb
- examples/extensions/add_sitelinks.rb
- examples/feeds/remove_flights_feed_item_attribute_value.rb
Change-Id: I4772adac2d4e450c41b484f638dc485780e1d9b5
> Fixing a few example failures.

- examples/feeds/create_feed_item_set.rb
- examples/feeds/get_feed_items_of_feed_item_set.rb
- examples/feeds/link_feed_item_set.rb
Change-Id: I18c2f8052a3dae826dc16753a9a5c070320fdb4f
> Adding examples for feed item sets.

- examples/remarketing/add_merchant_center_dynamic_remarketing_campaign.rb
- examples/shopping_ads/add_shopping_product_ad.rb
- examples/shopping_ads/add_shopping_product_listing_group_tree.rb
- examples/shopping_ads/add_shopping_smart_ad.rb
Change-Id: I76f4e36ba637899302365865cf86336f9f90f77e
> Another batch of example fixes.

- examples/extensions/remove_entire_sitelink_campaign_extension_setting.rb
Change-Id: I4828cf75614cb97e40679d15ba103c01f13356b9
> Fixing incorrect append operator.

- ChangeLog
- lib/google/ads/google_ads/version.rb
Change-Id: Ida0cab41829d84558fe41d8006e37fb7f9e56b0f
> Version bump for new minor release.

- lib/google/ads/google_ads/config.rb
Change-Id: I7853fca07f54d9324be901be9a34c4179a28b239
> Allowing http proxy to be set to nil.

- examples/account_management/update_user_access.rb
- examples/hotel_ads/add_hotel_listing_group_tree.rb
- examples/shopping_ads/add_shopping_product_listing_group_tree.rb
Fix code examples:
- Update User Access
- Add Hotel Listing Group Tree
- Add Shopping Product Listing Group Tree
> fix code examples

- ChangeLog
- lib/google/ads/google_ads/service_wrapper.rb
- lib/google/ads/google_ads/version.rb
- test/test_service_wrapper.rb
Change-Id: Ib63a41651a31e8c0c14adaa04ed35cb3b64d7f02
> Removing support for positional arguments.

- examples/account_management/create_customer.rb
- examples/advanced_operations/add_dynamic_page_feed.rb
- examples/remarketing/upload_store_sales_transactions.rb
Change-Id: I1d62c6a98f1af757844a458a6c790b16dd574787
> A few minor example fixes.

- google-ads-googleads.gemspec
Change-Id: Ia4624a4d4f1a4f6c6ea7bb4e246b2c7c36f46905
> Updating rake version for security alert.

- examples/advanced_operations/add_smart_display_ad.rb
- examples/basic_operations/add_campaigns.rb
- examples/extensions/add_google_my_business_location_extensions.rb
- examples/hotel_ads/add_hotel_ad.rb
- examples/remarketing/add_remarketing_action.rb
- examples/shopping_ads/add_shopping_smart_ad.rb
Change-Id: Ie38bef02b8debfc0b7e6008fed089fcbef6015a3
> Fix region tag names inconsistencies

- examples/account_management/reject_merchant_center_link.rb
- examples/advanced_operations/add_ad_customizer.rb
- examples/advanced_operations/add_local_campaign.rb
- examples/extensions/add_affiliate_location_extensions.rb
- examples/extensions/remove_entire_sitelink_campaign_extension_setting.rb
- examples/feeds/remove_flights_feed_item_attribute_value.rb
- examples/feeds/update_flights_feed_item_string_attribute_value.rb
- examples/hotel_ads/add_hotel_ad_group_bid_modifiers.rb
- examples/hotel_ads/add_hotel_listing_group_tree.rb
- examples/planning/forecast_reach.rb
- examples/remarketing/add_combined_rule_user_list.rb
- examples/remarketing/add_conversion_based_user_list.rb
- examples/remarketing/add_expression_rule_user_list.rb
- examples/remarketing/add_merchant_center_dynamic_remarketing_campaign.rb
- examples/remarketing/add_real_estate_feed.rb
- examples/remarketing/setup_advanced_remarketing.rb
- examples/remarketing/setup_remarketing.rb
- examples/remarketing/update_audience_targeting_restriction.rb
- examples/shopping_ads/add_shopping_product_listing_group_tree.rb
Change-Id: I885bd255938ff46b2eec463c63178dbcd5df79b8
> Add missing region tags

- lib/google/ads/google_ads/interceptors/logging_interceptor.rb
> add request id for non-streaming requests

- lib/google/ads/google_ads/google_ads_client.rb
This fixes #303 
Change-Id: I570d1a0e45956e8499e9485bf62fc09a532b5f12
> Fixing a bug with using service accounts for authentication.

- ChangeLog
- lib/google/ads/google_ads/utils/path_lookup_config.rb
- lib/google/ads/google_ads/version.rb
- test/test_path_lookup_util.rb
> add campaign_asset to path lookup util

- codegen/main.rb
- codegen/src/filters.rb
- codegen/templates/resources.rb.erb
- scripts/codegen.sh
> Fix name collisions

- lib/google/ads/google_ads/version.rb
> Version 14

- examples/advanced_operations/add_display_upload_ad.rb
- examples/advanced_operations/add_local_campaign.rb
- examples/advanced_operations/add_smart_display_ad.rb
- examples/misc/upload_image.rb
- examples/misc/upload_image_asset.rb
- examples/misc/upload_media_bundle.rb
- examples/remarketing/add_merchant_center_dynamic_remarketing_campaign.rb
Change-Id: I2709be91399a1784b2a5f9c28f8e586c0b7e27d8
> Updating URLs for various examples' media uploads.

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/usage_question.md
Change-Id: Id69fee3028c299de003f6045c5eeb90ab1c6eb73
> Adding issue templates for this repo.

- examples/advanced_operations/add_local_campaign.rb
- examples/advanced_operations/add_smart_campaign.rb
- examples/extensions/add_affiliate_location_extensions.rb
- examples/extensions/add_business_profile_location_extensions.rb
- examples/remarketing/set_up_advanced_remarketing.rb
- examples/remarketing/set_up_remarketing.rb
Change-Id: I348cc2d102ffba2b835820ccdf12591c21176455
> Various example renaming fixes.

- examples/remarketing/upload_conversion_enhancement.rb
Change-Id: Ia31ec196362f07fa48a720175a7d85021fc269bf
> Adding example for conversion enhancement.

- examples/advanced_operations/add_responsive_search_ad_with_ad_customizer.rb
Change-Id: I9a616733e4a70883f9d19843e28aa432baa4d37b
> Adding example for RSA ad customizers.

- examples/remarketing/upload_conversion_with_identifiers.rb
Change-Id: I766f3bb64c3d6348e81dac5d407e56cc091e5fac
> Adding example for conversion with user identifiers.

- examples/extensions/update_sitelink_campaign_extension_setting.rb
Fixes b/194098509
Change-Id: I45c6317332f230be70709bdddc191aa2a3fd014e
> Add update_sitelink_campaign_extension_setting example

- examples/remarketing/upload_store_sales_transactions.rb
Ref b/206736353
Ref b/206756887
Change-Id: I56b3c944778d71094f459f49f4e46f011740f584
> Add enable_warnings tags

- examples/remarketing/upload_conversion_with_identifiers.rb
Change-Id: Iaa18c55eca37fd70a4d0a7db039b75eae59ab34c
> Add region create_conversion tag

- examples/advanced_operations/add_performance_max_campaign.rb
Fixes b/207728913
Change-Id: I1eb095f5dc9f22a7ae0fe6b7a0bb523619ae5a62
> Add add_performance_max_campaign example

- README.md
Change-Id: Ib21231072f401ec68c1229c27da29433c1aa3b67
> Updating README for newly supported versions in 2022.

- examples/misc/upload_image_asset.rb
Change-Id: Iaefa9d92fb6dadc7b34784d7700b7b5072a95673
> Move name to asset

- examples/advanced_operations/add_performance_max_campaign.rb
- examples/basic_operations/add_campaigns.rb
- examples/remarketing/upload_offline_conversion.rb
- examples/shopping_ads/add_performance_max_retail_campaign.rb
Change-Id: If5d88c9f8efa35a407a197190a000604189fa74c
> A few example updates.

- examples/misc/navigate_search_result_pages_caching_tokens.rb
Change-Id: I76d851ffd94a7095fb6be90dff37af5567873ae5
> Adding example to demonstrate reusing page tokens.

- THIRD-PARTY-LICENCES.txt
- google-ads-googleads.gemspec
Change-Id: I05f5dd11eabae8e3d38145f4ea01e7a5b9c66245
> Adding text for third party dependency licenses.

- examples/basic_operations/search_for_google_ads_fields.rb
Change-Id: Idd5d73bbe442237dfa1f47dc142182516f5fe578
> Updating artifact metadata example to be clearer.

- examples/misc/set_custom_client_timeouts.rb
Change-Id: I27aa4996572ace07dae7dcb07f625e8f11af01ec
> Adding comment to custom timeout example.

- examples/campaign_management/validate_ad.rb
Change-Id: I8dea88012615c642d8e5abb37c559e4c62c71b87
> Updating validation example to use RSA instead of ETA.

- examples/planning/generate_historical_metrics.rb
Change-Id: Ib6fb47c7ca8431db981906eeee31f0514ffe1f88
> Adding example for historical metrics.

- examples/error_handling/handle_responsive_search_ad_policy_violations.rb
- examples/planning/forecast_reach.rb
Change-Id: Ib5e897a4f6501a7c75076c762a575da22971b8d4
> A few more example updates.

- google-ads-googleads.gemspec
Change-Id: If0255fa42f7463d4b35ad54de8612e890e57aec9
> Fixed gemspec for renamed file.

- examples/remarketing/add_customer_match_user_list.rb
Change-Id: Iac50ea05dd22a6b72f27187769179347c1689739
> Updating customer match example.

- README.md
> Add a gem <=> API mapping to the top of the README

- examples/hotel_ads/add_performance_max_for_travel_goals_campaign.rb
> Add PMax for Travel Goals example

- examples/remarketing/add_customer_match_user_list.rb
Updates implemented in Perl: https://github.com/googleads/google-ads-perl/blob/main/examples/remarketing/add_customer_match_user_list.pl
> Update tags in Customer Match example

- CHANGELOG.md
- codegen/spec/template_service_spec.rb
- lib/google/ads/google_ads/version.rb
> Release 14_0 version bump

- google-ads-googleads.gemspec
Fixes https://github.com/googleads/google-ads-ruby/issues/464
> Update gapic-common dep

- examples/remarketing/upload_offline_conversion.rb
> Demonstrate passing consent in offline conversion upload

- CHANGELOG.md
- Gemfile
- lib/google/ads/google_ads/version.rb
Change-Id: I244274f9faaee350f4d2cddee9e8ef39c6da5013
> Allow grpc 1.74.1 and beyond
